---
version: 2

plan:
  project-key: FAST
  key: FAST
  name: Demo FAST testing plan
  variables:
    secret_token: BAMSCRT@0@0@BD+8NIfWD4AtzHDwm3A5TF9YQOacU1npnP/2sw7MdoR5JIuBtMbsvvrJS1fI8AIkBZ2tFRKfSYiQbN0hrf9APV8JUDDTKu5CwGlZxfseou0=

stages:
  - building:
      - build
  - testing:
      manual: false
      final: false
      jobs:
        - tests
  - cleaning:
      final: true
      jobs:
        - cleanup

build:
  key: BLD
  tasks:
    - inject-variables:
        secret_token: BAMSCRT@0@0@BD+8NIfWD4AtzHDwm3A5TF9YQOacU1npnP/2sw7MdoR5JIuBtMbsvvrJS1fI8AIkBZ2tFRKfSYiQbN0hrf9APV8JUDDTKu5CwGlZxfseou0=
    - script: ./build.sh

tests:
  key: TST
  tasks:
    interpreter: /bin/sh
      scripts:
        - docker-compose up -d dvwa fast selenium
        - docker-compose run --service-ports test
        - docker-compose run -e CI_MODE=testing -e TEST_RUN_URI=http://dvwa:80 fast

cleanup:
  key: CLN
  tasks:
    - script:
        - docker-compose down
